# Generated by Django 4.2 on 2023-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
            ],
        ),
    ]
